# Generated by Django 4.1.7 on 2023-02-23 19:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('englishdic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dic',
            options={'ordering': ['-date_added']},
        ),
        migrations.AddField(
            model_name='dic',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dic',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dic',
            name='word',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
