# Generated by Django 4.1.7 on 2023-03-03 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('englishdic', '0002_alter_dic_options_dic_date_added_alter_dic_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dic',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
